### ISSUE TITLE
Add functions for running lots of lists in parallel + graphing results

### ISSUE THREAD

**Issue by NathanSkene** [NathanSkene/EWCE#24]

**Comment by bschilder** [comment]
This is now covered by `MulltiEWCE`. Originally, this was designed to only work with the HPO gene lists, but I have since extended it to work with any gene lists provided in a table. 
https://github.com/neurogenomics/MultiEWCE/blob/master/R/gen_results.R

This can be done by adding custom inputs to the following arguments within `gen_results`:
```
gene_data,
list_name_column = "Phenotype",
gene_column = "Gene",
```
