### ISSUE TITLE
Enable meta-data (such as that generated by `get.celltype.table` and Brian's `plot_gene_metrics`) to be stored in the CTD

### ISSUE THREAD

**Issue by NathanSkene** [NathanSkene/EWCE#30]
Will probably break most existing functions that expect ctd[[1]] to have $specificity, so might want to adapt so ctd[[1]] has meta-data, and ctd[[2]] has the meanexp/specificity data.

Would need to cascade any changes to magma_celltyping as well

**Comment by bschilder** [comment]
The way i worked around this is to simply store is to simply store the metadata within a given level. This can be a bit redundant for some metadata types, but if they're small enough it doesn't affect the overall size of the CTD (e.g. EWCE version, orthogene version, species).

For larger objects like plots, it seems more economical to me to have EWCE functions recreate these rather than store them directly in the CTD. If you really want a CTD stored as a bundle with plots and such, you can always save it as a RDS object with each of these elements in a list:

```R
out <- list(ctd=ewceData::ctd(),
plot1=plot2,
plot2=plot2)
saveRDS(out, <out_path>)
```
