### ISSUE TITLE
Expression in cell type (%)

### ISSUE THREAD

**Issue by h1hui** [NathanSkene/EWCE#63]
Hi there,

Thank you for doing such a good job developing this library. 

I was reading the reference paper:
[Skene, et al. Identification of Vulnerable Cell Types in Major Brain Disorders Using Single Cell Transcriptomes and Expression Weighted Cell Type Enrichment.Front. Neurosci, 2016.](https://www.frontiersin.org/articles/10.3389/fnins.2016.00016/full)

And I would like to plot the same expression in celltype (%) plot, but how can I do it with the development version of this library? Is it still a feature?
<img width="728" alt="Screen Shot 2022-05-11 at 11 34 22 AM" src="https://user-images.githubusercontent.com/33336127/167921490-1b2d27c7-5181-4588-9c1e-4c1b6c625a0d.png">

Thanks,
Ashley

**Comment by bschilder** [comment]
I think this might be what you're looking for:
https://nathanskene.github.io/EWCE/reference/generate_bootstrap_plots.html

**Comment by h1hui** [comment]
Thank you for your reply. However I ran into an error while plotting.
```
> plot_file_path <- EWCE::generate_bootstrap_plots(
+     sct_data = ctd,
+     hits = hits,
+     genelistSpecies = "human",
+     sctSpecies = "human",
+     output_species = "human",
+     method = "homologene",
+     reps = 1000,
+     annotLevel = 1,
+     full_results = full_results,
+     listFileName = "",
+     savePath = tempdir(),
+     verbose = TRUE
+ )
Retrieving all genes using: homologene.
Retrieving all organisms available in homologene.
Mapping species name: human
Common name mapping found for human
1 organism identified from search: 9606
Gene table with 19,129 rows retrieved.
Returning all 19,129 genes from human.
Standardising sct_data.
Converting to sparse matrix.
Converting to sparse matrix.
Aligning celltype names with standardise_ctd format.
Error in exp_mats[[cc]][s, ] <- sort(expD[, cc]) : 
  number of items to replace is not a multiple of replacement length
```
Where do you suggest the problem lies?

Thanks,
Ashley

**Comment by NathanSkene** [comment]
Have you tried it using the example datasets?

From: h1hui ***@***.***>
Date: Friday, 13 May 2022 at 20:00
To: NathanSkene/EWCE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [NathanSkene/EWCE] Expression in cell type (%) (Issue #63)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Thank you for your reply. However I ran into an error while plotting.

> plot_file_path <- EWCE::generate_bootstrap_plots(

+     sct_data = ctd,

+     hits = hits,

+     genelistSpecies = "human",

+     sctSpecies = "human",

+     output_species = "human",

+     method = "homologene",

+     reps = 1000,

+     annotLevel = 1,

+     full_results = full_results,

+     listFileName = "",

+     savePath = tempdir(),

+     verbose = TRUE

+ )

Retrieving all genes using: homologene.

Retrieving all organisms available in homologene.

Mapping species name: human

Common name mapping found for human

1 organism identified from search: 9606

Gene table with 19,129 rows retrieved.

Returning all 19,129 genes from human.

Standardising sct_data.

Converting to sparse matrix.

Converting to sparse matrix.

Aligning celltype names with standardise_ctd format.

Error in exp_mats[[cc]][s, ] <- sort(expD[, cc]) :

  number of items to replace is not a multiple of replacement length

Where do you suggest the problem lies?

Thanks,
Ashley

**Comment by h1hui** [comment]
Yes I tried. It ran without a problem, but I still don't know what's causing the error in my dataset.

**Comment by bschilder** [comment]
@h1hui please follow the Bug template provided when you submit a new issue. That way, you can see the steps necessary to provide a reproducible example

**Comment by bschilder** [comment]
Looks like you started a new Issue on this topic here. Closing this one to avoid redundancy #66

**Comment by NathanSkene** [comment]
Hey,

Pretty sure it’s still implemented in this function:

https://github.com/NathanSkene/EWCE/blob/master/R/generate_bootstrap_plots.r

Been a good while since I’ve used it though, so do let me know if I’m wrong.

Best,

Nathan

From: h1hui ***@***.***>
Date: Wednesday, 11 May 2022 at 19:34
To: NathanSkene/EWCE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NathanSkene/EWCE] Expression in cell type (%) (Issue #63)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Hi there,

Thank you for doing such a good job developing this library.

I was reading the reference paper:
Skene, et al. Identification of Vulnerable Cell Types in Major Brain Disorders Using Single Cell Transcriptomes and Expression Weighted Cell Type Enrichment.Front. Neurosci, 2016.<https://www.frontiersin.org/articles/10.3389/fnins.2016.00016/full>

And I would like to plot the same expression in celltype (%) plot, but how can I do it with the development version of this library? Is it still a feature?
[Screen Shot 2022-05-11 at 11 34 22 AM]<https://user-images.githubusercontent.com/33336127/167921490-1b2d27c7-5181-4588-9c1e-4c1b6c625a0d.png>

Thanks,
Ashley
