### ISSUE TITLE
generate_celltype_data with raw or SCTransformed data

### ISSUE THREAD

**Issue by artemisiat** [NathanSkene/EWCE#68]
Thank you for this comprehensive package.
I was wondering whether you recommend using raw or other assay (sct/integrated) counts as input for the construction of the CellTypeData file.
Thanks!

**Comment by Al-Murphy** [comment]
Hey, great to hear you are finding the package useful! We advise using normalized gene count matrix with EWCE, this is described in our extended vignette documentation: https://nathanskene.github.io/EWCE/articles/extended.html#create-a-celltypedataset. Here we discuss using scTransform to normalise for differences due to cell size, then linearly scale. We have functionality for this:

```
cortex_mrna$exp_scT_normed <- EWCE::sct_normalize(cortex_mrna$exp) 
```

**Comment by Al-Murphy** [comment]
I'm not sure what the differences are but other normalisation approaches should also be appropriate

**Comment by artemisiat** [comment]
thanks!
